### PR TITLE
Add: LICENSE File

### PR DESCRIPTION
**Pull request by Manoj-Paramsetti**
## Related Issues or Pull Requests

#5 

### Brief explanation of the Problem statement

In this pull request, I added the BSD 3-Clause License in this repository

### Checklist

- [ ] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

#### File(s) Added / Modified

- New file: `LICENSE`

### CODE REVIEW

**Review by KamalDGRT — CHANGES_REQUESTED** [review]
Instead of your name, in the LICENSE file, mention the Club's name.

**Comment by Manoj-Paramsetti** [comment]
**Oops! Adhu Maranthuta Vaathi**

**Comment by KamalDGRT** [comment]
Understandable

**Review by KamalDGRT — APPROVED** [review]
Good work @Manoj-Paramsetti ✨

**Pull request merged**
